-- ============================================================================
-- 電子版（顧客「電子版」システム）MySQL のローカル擬似データベース初期化スクリプト。
-- dokusya-sync バッチが読み取る `users`（113列）/ `ja`（24列）を再現する。
-- 本番の DENSHIBAN_DB_*（read-only, cmsDB）に対応するローカルモック。
-- ※ 型は顧客提供のサンプルレコードから推定（フラグ系は VARCHAR、日時は DATETIME）。
-- ============================================================================
CREATE DATABASE IF NOT EXISTS cmsDB
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cmsDB;

-- ---------------------------------------------------------------------------
-- users（読者マスタ, 113列）
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id                        BIGINT       NOT NULL AUTO_INCREMENT,
  email                     VARCHAR(255) NULL,
  password                  VARCHAR(255) NULL,
  group_id                  INT          NULL,
  activated                 TINYINT      NULL,
  activated_at              DATETIME     NULL,
  last_login                DATETIME     NULL,
  remember_token            VARCHAR(255) NULL,
  first_name                VARCHAR(255) NULL,
  last_name                 VARCHAR(255) NULL,
  first_kana                VARCHAR(255) NULL,
  last_kana                 VARCHAR(255) NULL,
  attached                  VARCHAR(255) NULL,
  company                   VARCHAR(255) NULL,
  belong                    VARCHAR(255) NULL,
  department                VARCHAR(255) NULL,
  payment_id                INT          NULL,
  payment_acid              VARCHAR(255) NULL,
  payment_gid               VARCHAR(255) NULL,
  payment_opened_at         DATETIME     NULL,
  payment_next_at           DATETIME     NULL,
  payment_cycle             INT          NULL,
  fee                       INT          NULL,
  uuid                      VARCHAR(64)  NULL,
  subscribe_act             INT          NULL,
  trialed_at                INT          NULL,
  trial_email               VARCHAR(255) NULL,
  zip1                      VARCHAR(16)  NULL,
  zip2                      VARCHAR(16)  NULL,
  pref_id                   INT          NULL,
  addr                      VARCHAR(255) NULL,
  city                      VARCHAR(255) NULL,
  building                  VARCHAR(255) NULL,
  tel1                      VARCHAR(32)  NULL,
  tel2                      VARCHAR(32)  NULL,
  tel3                      VARCHAR(32)  NULL,
  birthyear                 INT          NULL,
  birthmonth                INT          NULL,
  birthday                  INT          NULL,
  melmaga                   TINYINT      NULL,
  thumbnail                 INT          NULL,
  weather                   VARCHAR(255) NULL,
  keyword1                  VARCHAR(255) NULL,
  keyword2                  VARCHAR(255) NULL,
  keyword3                  VARCHAR(255) NULL,
  permission                INT          NULL,
  managed                   INT          NULL,
  session_id                VARCHAR(255) NULL,
  memo                      TEXT         NULL,
  created_at                DATETIME     NULL,
  updated_at                DATETIME     NULL,
  deleted_at                DATETIME     NULL,
  pref                      INT          NULL,
  JACd                      VARCHAR(32)  NULL,
  treatment                 VARCHAR(8)   NULL,
  collecting                VARCHAR(255) NULL,
  application               VARCHAR(8)   NULL,
  first_login               VARCHAR(8)   NULL,
  approval                  VARCHAR(8)   NULL,
  subscribe_flg             VARCHAR(8)   NULL,
  branch                    VARCHAR(255) NULL,
  profession                VARCHAR(255) NULL,
  products                  VARCHAR(255) NULL,
  sex                       VARCHAR(8)   NULL,
  subscribe_trigger         VARCHAR(255) NULL,
  store                     VARCHAR(255) NULL,
  ja_position               VARCHAR(255) NULL,
  status                    VARCHAR(8)   NULL,
  status_view               VARCHAR(8)   NULL,
  member_type               VARCHAR(8)   NULL,
  payment_start_ym          VARCHAR(16)  NULL,
  payment_end_ym            VARCHAR(16)  NULL,
  application_date          DATETIME     NULL,
  approval_date             DATETIME     NULL,
  member_type_view          VARCHAR(8)   NULL,
  Campagna_flg              VARCHAR(8)   NULL,
  profession_and_ja         VARCHAR(8)   NULL,
  profession_and_agri       VARCHAR(8)   NULL,
  others_profession         VARCHAR(255) NULL,
  others_products           VARCHAR(255) NULL,
  others_subscribe_trigger  VARCHAR(255) NULL,
  remarks1                  TEXT         NULL,
  remarks2                  TEXT         NULL,
  remarks3                  TEXT         NULL,
  remarks4                  TEXT         NULL,
  remarks5                  TEXT         NULL,
  customer_id               VARCHAR(255) NULL,
  customer_card_id          VARCHAR(255) NULL,
  running_id                VARCHAR(255) NULL,
  reserve_activated_at      DATETIME     NULL,
  merger_jacd               VARCHAR(32)  NULL,
  paper_application_date    DATETIME     NULL,
  paper_zip                 VARCHAR(16)  NULL,
  paper_pref_id             INT          NULL,
  paper_addr                VARCHAR(255) NULL,
  paper_city                VARCHAR(255) NULL,
  paper_building            VARCHAR(255) NULL,
  reading_flg               VARCHAR(8)   NULL,
  permission_flg            VARCHAR(8)   NULL,
  paper_permission_dt       VARCHAR(32)  NULL,
  chg_paper_addr_dt         VARCHAR(32)  NULL,
  ShopCd                    VARCHAR(32)  NULL,
  ShopNm                    VARCHAR(255) NULL,
  paper_payment_start_ym    VARCHAR(16)  NULL,
  paper_payment_end_ym      VARCHAR(16)  NULL,
  paper_memo                TEXT         NULL,
  paper_settlement_flg      VARCHAR(8)   NULL,
  cancel_date               DATETIME     NULL,
  cancel_flg                VARCHAR(8)   NULL,
  cancel_process_date       DATETIME     NULL,
  next_plan_cd              VARCHAR(16)  NULL,
  next_approval_date        VARCHAR(32)  NULL,
  subscription_status       VARCHAR(32)  NULL,
  PRIMARY KEY (id),
  KEY idx_users_updated_at (updated_at),
  KEY idx_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (
  id, email, password, group_id, activated, activated_at, last_login, remember_token,
  first_name, last_name, first_kana, last_kana, attached, company, belong, department,
  payment_id, payment_acid, payment_gid, payment_opened_at, payment_next_at, payment_cycle,
  fee, uuid, subscribe_act, trialed_at, trial_email, zip1, zip2, pref_id, addr, city,
  building, tel1, tel2, tel3, birthyear, birthmonth, birthday, melmaga, thumbnail, weather,
  keyword1, keyword2, keyword3, permission, managed, session_id, memo, created_at, updated_at,
  deleted_at, pref, JACd, treatment, collecting, application, first_login, approval,
  subscribe_flg, branch, profession, products, sex, subscribe_trigger, store, ja_position,
  status, status_view, member_type, payment_start_ym, payment_end_ym, application_date,
  approval_date, member_type_view, Campagna_flg, profession_and_ja, profession_and_agri,
  others_profession, others_products, others_subscribe_trigger, remarks1, remarks2, remarks3,
  remarks4, remarks5, customer_id, customer_card_id, running_id, reserve_activated_at,
  merger_jacd, paper_application_date, paper_zip, paper_pref_id, paper_addr, paper_city,
  paper_building, reading_flg, permission_flg, paper_permission_dt, chg_paper_addr_dt,
  ShopCd, ShopNm, paper_payment_start_ym, paper_payment_end_ym, paper_memo,
  paper_settlement_flg, cancel_date, cancel_flg, cancel_process_date, next_plan_cd,
  next_approval_date, subscription_status
) VALUES (
  1, 'nextep01@nextep-sol.jp', '672b4b1f86368305996ac0fdbda9a80a', 1, 1,
  '2018-10-15 09:13:08', '2026-06-02 08:32:09',
  'v3FgpNAY5Wz0lBVY2QnzZnulgZbRR9ffNvOVXqMal6ZtD40h5ROrMqhXMa6j',
  'ネクステップ', '０１', 'ねくすてっぷ', '０１', NULL, NULL, NULL, NULL,
  1, NULL, NULL, NULL, NULL, 0,
  0, '7748f61c-7593-42ca-a59e-f6a5a48af55a', 1, 2147483647, 'nextep01@nextep-sol.jp',
  '0000000', '', 13, 'あ', '123',
  '', '1234567890', '', '', NULL, 0, 0, 0, 0, NULL,
  NULL, NULL, NULL, 1, 1, '697f1c22ce6c7dfd6b1c50e0e3f6a982e70c5f94', '',
  '2018-10-15 09:13:08', '2026-06-02 08:32:09',
  NULL, 1, '', '0', '', '1', '1', '9',
  '1', '', NULL, NULL, NULL, NULL, '', '',
  '2', '0', '2', '', '', '2021-12-07 00:42:05',
  NULL, '0', '0', '0', '0',
  NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL,
  NULL, '0', '0', '', '',
  NULL, NULL, '', '', NULL,
  '0', NULL, '0', NULL, '0',
  '', ''
);

-- ---------------------------------------------------------------------------
-- ja（JAマスタ, 24列）
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS ja;
CREATE TABLE ja (
  id                  BIGINT       NOT NULL AUTO_INCREMENT,
  JACd                VARCHAR(32)  NULL,
  JANm                VARCHAR(255) NULL,
  JANmR               VARCHAR(255) NULL,
  JANmK               VARCHAR(255) NULL,
  DeptNm              VARCHAR(255) NULL,
  TantoNm             VARCHAR(255) NULL,
  TantoNmK            VARCHAR(255) NULL,
  Tel                 VARCHAR(32)  NULL,
  Fax                 VARCHAR(32)  NULL,
  PrefCd              VARCHAR(8)   NULL,
  JAKbnCd             VARCHAR(8)   NULL,
  ja_mail_address_01  VARCHAR(255) NULL,
  ja_mail_address_02  VARCHAR(255) NULL,
  ja_mail_address_03  VARCHAR(255) NULL,
  ja_mail_address_04  VARCHAR(255) NULL,
  ja_mail_address_05  VARCHAR(255) NULL,
  nationwide_flg      VARCHAR(8)   NULL,
  ShowOrder           INT          NULL,
  ShowFlag            VARCHAR(8)   NULL,
  created_at          DATETIME     NULL,
  updated_at          DATETIME     NULL,
  list_show_flag      VARCHAR(8)   NULL,
  ParentJACd          VARCHAR(32)  NULL,
  PRIMARY KEY (id),
  KEY idx_ja_jacd (JACd)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- サンプル（顧客サンプル未提供のため代表値で1件投入）。
INSERT INTO ja (
  id, JACd, JANm, JANmR, JANmK, DeptNm, TantoNm, TantoNmK, Tel, Fax, PrefCd, JAKbnCd,
  ja_mail_address_01, ja_mail_address_02, ja_mail_address_03, ja_mail_address_04,
  ja_mail_address_05, nationwide_flg, ShowOrder, ShowFlag, created_at, updated_at,
  list_show_flag, ParentJACd
) VALUES (
  1, '1301002001', 'JA東京中央', 'JAトウキョウチュウオウ', 'ｼﾞｪｲｴｰﾄｳｷｮｳﾁｭｳｵｳ',
  '営業部', '農協太郎', 'ﾉｳｷｮｳﾀﾛｳ', '03-3201-0001', '03-3201-0009', '13', '1',
  'info@ja-tokyo.example.jp', '', '', '', '', '0', 1, '1',
  '2018-10-15 09:13:08', '2026-06-02 08:32:09', '1', ''
);
