/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * agrinews API
 * クラウド版購読者管理システム API
 * OpenAPI spec version: 1.0
 */
import { customInstance } from '.././axios-instance';



  export const getHealth = () => {
/**
 * @summary Liveness check
 */
const healthControllerCheck = (
    
 ) => {
      return customInstance<void>(
      {url: `/health`, method: 'GET'
    },
      );
    }
  /**
 * @summary Readiness check (DB connection)
 */
const healthControllerReadiness = (
    
 ) => {
      return customInstance<void>(
      {url: `/health/ready`, method: 'GET'
    },
      );
    }
  return {healthControllerCheck,healthControllerReadiness}};
export type HealthControllerCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHealth>['healthControllerCheck']>>>
export type HealthControllerReadinessResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHealth>['healthControllerReadiness']>>>
