-- ============================================================================
-- seed-chuokai-zg-snapshot.sql
--   Snapshot SEED của account `chuokai_zg` + toàn bộ dữ liệu liên quan
--   (JA / 管理支店 / 販売店 / 単価 / 独giả t_dokusya / lịch sử t_dokusya_rireki).
--
-- Mục đích : chuyển sang DB MỚI (đã chạy migration) hoặc reset DB hiện tại mà
--            vẫn có nguyên bộ dữ liệu độc giả của chuokai_zg để test
--            (SCR-020/021 口座振替, SCR-026 名簿, SCR-028/029 増減連絡票/通知…).
--
-- Đặc điểm :
--   • IDEMPOTENT — xóa đúng graph chuokai_zg (theo ja_code='JAZG9001' +
--     login_id='chuokai_zg') rồi chèn lại. Chạy nhiều lần đều ra cùng kết quả.
--   • GIỮ NGUYÊN ID gốc (ja_id=108, account_id=29, dokusya 172–176, …) để
--     khớp các script verify/test khác. Trên DB mới các ID này còn trống.
--   • Tự fix sequence sau khi chèn (setval = MAX(id)).
--   • Snapshot phản ánh TRẠNG THÁI HIỆN TẠI của DB dev (gồm cả thay đổi địa chỉ
--     dokusya 176). Sinh tự động từ live DB — KHÔNG sửa tay phần INSERT.
--
-- Phụ thuộc (phải có sẵn, do migration seed): m_todofuken (code 13),
--   m_roles (role_id=3 CHUOKAI), m_code, m_permissions…
--
-- Chạy:
--   docker exec -i agrinews-postgres-1 psql -U postgres -d <db> \
--     -v ON_ERROR_STOP=1 < docs/zougen-028-029-and-validate-scr-016/seed-chuokai-zg-snapshot.sql
--
-- Login: chuokai_zg / admin@1234567   (password_hash giữ nguyên từ snapshot)
-- ============================================================================

BEGIN;

-- ── 1) CLEANUP graph cũ (children → parent, NULL-safe) ──────────────────────
DELETE FROM t_dokusya_rireki WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code='JAZG9001');
DELETE FROM t_dokusya        WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code='JAZG9001');
DELETE FROM t_mfa_otp   WHERE account_id IN (SELECT account_id FROM m_account WHERE login_id='chuokai_zg');
DELETE FROM t_log       WHERE account_id IN (SELECT account_id FROM m_account WHERE login_id='chuokai_zg');
DELETE FROM t_login_log WHERE account_id IN (SELECT account_id FROM m_account WHERE login_id='chuokai_zg');
DELETE FROM m_account   WHERE login_id='chuokai_zg';
DELETE FROM m_hanbaiten WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code='JAZG9001');
DELETE FROM m_tanka     WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code='JAZG9001');
DELETE FROM m_shiten    WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code='JAZG9001');
DELETE FROM m_kanri_shiten WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code='JAZG9001');
DELETE FROM m_ja        WHERE ja_code='JAZG9001';

-- ── 2) INSERT snapshot (sinh tự động, giữ nguyên ID) ────────────────────────
-- ---- m_ja ----
INSERT INTO m_ja (ja_id,ja_code,ja_name,ja_name_kana,todofuken_code,yubin_no,address,tel,fax,email,tanto_busho,tanto_name,jastem_itakusha_code,jastem_itakusha_name,jastem_ja_code,jastem_ja_name,chuokai_flg,zei_kubun,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('108', 'JAZG9001', '増減検証JA', 'ｿﾞｳｹﾞﾝｹﾝｼｮｳｼﾞｪｲｴｰ', '13', '1000001', '東京都千代田区1-1-1', '03-0000-1111', '03-0000-0002', '', '', '', '', '', '', '', 'false', '1', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');

-- ---- m_tanka ----
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('159', '108', 'T001', '1', '新聞購読料 月額', '3500', '3182', '10.00', '2026-01-10', NULL, '', 'true', 'false', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('163', '108', 'T002', '2', '配達手数料 月額', '350', '318', '10.00', '2026-01-10', NULL, '', 'true', 'false', NULL, '2026-06-26 03:32:15.684711+09', 'PATCH_2021', '2026-06-26 03:32:15.684711+09', 'PATCH_2021');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('164', '108', 'T003', '1', '新聞購読料 月額(セット)', '4200', '3819', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('165', '108', 'T004', '1', '新聞購読料 月額(統合版)', '3000', '2728', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('166', '108', 'T005', '1', '新聞購読料 月額(日曜版)', '1200', '1091', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('167', '108', 'T006', '1', '新聞購読料 月額(夕刊)', '1800', '1637', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('168', '108', 'T007', '1', '新聞購読料 月額(電子+紙)', '4800', '4365', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('169', '108', 'T008', '2', '配達手数料 月額(市内)', '400', '364', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('170', '108', 'T009', '2', '配達手数料 月額(郊外)', '600', '546', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('171', '108', 'T010', '2', '配達手数料 月額(山間部)', '1000', '909', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('172', '108', 'T011', '2', '配達手数料 月額(離島)', '1500', '1364', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_tanka (tanka_id,ja_id,tanka_code,tanka_type,tanka_name,kingaku_zeikomi,kingaku_zeinuki,tax_rate,tekiyo_start_date,tekiyo_end_date,biko,active_flg,campaign_flg,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('173', '108', 'T012', '2', '配達手数料 月額(早朝便)', '700', '637', '10.00', '2025-04-01', NULL, '', 'true', 'false', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');

-- ---- m_kanri_shiten ----
INSERT INTO m_kanri_shiten (kanri_shiten_id,ja_id,kanri_shiten_code,kanri_shiten_name,kanri_shiten_name_kana,yubin_no,todofuken_code,address,tel,fax,paper_flg,denshi_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('166', '108', '113-9001-001', '増減検証管理支店A', 'ｿﾞｳｹﾞﾝｹﾝｼｮｳｶﾝﾘｼﾃﾝｴｰ', '1000001', '13', '東京都千代田区A', '03-0000-1001', '03-0000-1002', 'false', 'false', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO m_kanri_shiten (kanri_shiten_id,ja_id,kanri_shiten_code,kanri_shiten_name,kanri_shiten_name_kana,yubin_no,todofuken_code,address,tel,fax,paper_flg,denshi_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('167', '108', '113-9001-002', '増減検証管理支店B', 'ｿﾞｳｹﾞﾝｹﾝｼｮｳｶﾝﾘｼﾃﾝﾋﾞｰ', '1000001', '13', '東京都千代田区B', '03-0000-2001', '03-0000-2002', 'false', 'false', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');

-- ---- m_shiten ----
INSERT INTO m_shiten (shiten_id,ja_id,shiten_code,shiten_name,shiten_name_kana,kinyu_shiten_flg,jastem_toriatsukai_tenpo_code,jastem_tenpo_name,jastem_tyokin_shubetsu,jastem_koza_no,kanri_shiten_id,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('166', '108', 'ST9001', '増減検証支店A', 'ｿﾞｳｹﾞﾝｼﾃﾝｴｰ', 'false', '', '', '', '', '166', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO m_shiten (shiten_id,ja_id,shiten_code,shiten_name,shiten_name_kana,kinyu_shiten_flg,jastem_toriatsukai_tenpo_code,jastem_tenpo_name,jastem_tyokin_shubetsu,jastem_koza_no,kanri_shiten_id,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('167', '108', 'ST9002', '増減検証支店B', 'ｿﾞｳｹﾞﾝｼﾃﾝﾋﾞｰ', 'false', '', '', '', '', '167', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO m_shiten (shiten_id,ja_id,shiten_code,shiten_name,shiten_name_kana,kinyu_shiten_flg,jastem_toriatsukai_tenpo_code,jastem_tenpo_name,jastem_tyokin_shubetsu,jastem_koza_no,kanri_shiten_id,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('171', '108', '010', 'STBank', '', 'true', '010', 'ABCE', '1', '1234456', '166', '', NULL, '2026-06-26 02:44:08.834529+09', '29', '2026-06-26 02:44:08.834529+09', '29');

-- ---- m_hanbaiten ----
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('24', '108', 'HB001', '増減販売店1', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ1', '', '13', '', '', '', '', '', '2', '163', '1', NULL, NULL, '0001', 'みずほ銀行', '001', '本店', '1', '9001', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ1', 'false', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('25', '108', 'HB002', '増減販売店2', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ2', 'T1234567890123', '13', '', '', '', '', '', '1', '163', '3', NULL, NULL, '0001', 'みずほ銀行', '002', '丸の内', '1', '9002', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ2', 'false', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('26', '108', 'HB003', '増減販売店3(廃店)', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ3', '', '13', '', '', '', '', '', '2', '163', '6', NULL, NULL, '0001', 'みずほ銀行', '003', '廃店', '1', '9003', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ3', 'true', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('36', '108', 'HB004', '追加販売店4', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ4', 'T4000000000004', '13', '', '', '', '', '', '1', '169', NULL, NULL, NULL, '0001', 'みずほ銀行', '011', '秋葉原', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('37', '108', 'HB005', '追加販売店5', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ5', 'T4000000000005', '13', '', '', '', '', '', '1', '169', NULL, NULL, NULL, '0005', '三菱UFJ銀行', '012', '上野', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('38', '108', 'HB006', '追加販売店6', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ6', 'T4000000000006', '13', '', '', '', '', '', '1', '169', NULL, NULL, NULL, '0009', '三井住友銀行', '013', '浅草', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('39', '108', 'HB007', '追加販売店7', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ7', 'T4000000000007', '13', '', '', '', '', '', '1', '169', NULL, NULL, NULL, '0001', 'みずほ銀行', '014', '錦糸町', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('40', '108', 'HB008', '追加販売店8', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ8', 'T4000000000008', '13', '', '', '', '', '', '2', '169', NULL, NULL, NULL, '0005', '三菱UFJ銀行', '015', '新宿', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('41', '108', 'HB009', '追加販売店9', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ9', 'T4000000000009', '13', '', '', '', '', '', '2', '169', NULL, NULL, NULL, '0009', '三井住友銀行', '016', '渋谷', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('42', '108', 'HB010', '追加販売店10', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ10', 'T4000000000010', '13', '', '', '', '', '', '1', '169', NULL, NULL, NULL, '0001', 'みずほ銀行', '017', '池袋', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('43', '108', 'HB011', '追加販売店11', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ11', 'T4000000000011', '13', '', '', '', '', '', '1', '169', NULL, NULL, NULL, '0005', '三菱UFJ銀行', '018', '品川', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('44', '108', 'HB012', '追加販売店12', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ12', 'T4000000000012', '13', '', '', '', '', '', '2', '169', NULL, NULL, NULL, '0009', '三井住友銀行', '019', '目黒', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO m_hanbaiten (hanbaiten_id,ja_id,hanbaiten_code,hanbaiten_name,hanbaiten_name_kana,torihikisaki_no,todofuken_code,yubin_no,address,tel,fax,shocho_name,itaku_kubun,haitatsuryo_tanka_id,haitatsuryo_shiharai_cycle,furikomi_tesuryo_futan_kubun,furikomi_tesuryo,bank_code,bank_name,bank_branch_code,bank_branch_name,yokin_shubetsu,koza_no,koza_meigi,haiten_flg,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('45', '108', 'HB013', '追加販売店13', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ13', 'T4000000000013', '13', '', '', '', '', '', '1', '169', NULL, NULL, NULL, '0001', 'みずほ銀行', '020', '中野', NULL, '', '', 'false', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');

-- ---- m_account ----
INSERT INTO m_account (account_id,login_id,password_hash,account_name,role_id,ja_id,kanri_shiten_id,todofuken_code,paper_flg,denshi_flg,email,sub_email_1,sub_email_2,sub_email_3,password_updated_at,last_login_at,login_failure_count,mfa_enable_flg,account_lock_flg,account_lock_at,biko,deleted_at,created_at,created_by,updated_at,updated_by) VALUES ('29', 'chuokai_zg', '$2b$10$n4LPqi8Ix8.LVTNqeIZJb.aKAdY8mGfrwbiCxdQ17E7bLPY/24qaG', '増減検証中央会アカウント', '3', '108', NULL, '13', 'true', 'true', 'chuokai_zg@agrinews.jp', '', '', '', NULL, '2026-06-28 22:37:12.304+09', '0', 'false', 'false', NULL, '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-28 22:37:12.306065+09', 'SEED_ZG');

-- ---- t_dokusya ----
INSERT INTO t_dokusya (dokusya_id,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,rireki_no,deleted_at,created_at,created_by,updated_at,updated_by,denshi_shonin_status,denshi_kaiin_id) VALUES ('172', '108', '166', '166', '', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '3', '1000000', '02', 'Phường Hà Đông', 'Địa chỉ thứ 2', '', 'DC-LH-002', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '24', '164', '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '2', NULL, '2026-06-30 01:33:21.721161+09', '29', '2026-06-30 02:26:55.481488+09', '29', NULL, NULL);
INSERT INTO t_dokusya (dokusya_id,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,rireki_no,deleted_at,created_at,created_by,updated_at,updated_by,denshi_shonin_status,denshi_kaiin_id) VALUES ('173', '108', '166', '166', 'TC-0000002', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '5', '1000001', '02', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '25', '164', '0', '3', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '1', NULL, '2026-06-30 01:35:41.014243+09', '29', '2026-06-30 01:35:41.014243+09', '29', NULL, NULL);
INSERT INTO t_dokusya (dokusya_id,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,rireki_no,deleted_at,created_at,created_by,updated_at,updated_by,denshi_shonin_status,denshi_kaiin_id) VALUES ('174', '108', '166', '166', 'TC-0000003', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '2', '1000003', '01', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '24', '167', '0', '5', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '', '', '1', NULL, '2026-06-30 01:45:14.520668+09', '29', '2026-06-30 01:45:14.520668+09', '29', NULL, NULL);
INSERT INTO t_dokusya (dokusya_id,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,rireki_no,deleted_at,created_at,created_by,updated_at,updated_by,denshi_shonin_status,denshi_kaiin_id) VALUES ('175', '108', '166', '166', 'TC-0000004', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '1', '1000004', '02', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '24', '167', '0', '5', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '1', NULL, '2026-06-30 01:48:04.762104+09', '29', '2026-06-30 01:48:04.762104+09', '29', NULL, NULL);
INSERT INTO t_dokusya (dokusya_id,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,rireki_no,deleted_at,created_at,created_by,updated_at,updated_by,denshi_shonin_status,denshi_kaiin_id) VALUES ('176', '108', '167', '167', 'TC-0000005', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '6', '1000006', '04', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'false', '1133333', '05', 'Phường Đông Anh', 'Địa chỉ haitatsu thứ 2', '', 'LH haitatsu 2', '', '今日', '今日', 'べとなむ', 'べとなむ', '24', '166', '0', '5', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '2', NULL, '2026-06-30 02:07:01.731606+09', '29', '2026-06-30 02:49:48.856253+09', '29', NULL, NULL);

-- ---- t_dokusya_rireki ----
INSERT INTO t_dokusya_rireki (dokusya_rireki_id,dokusya_id,rireki_no,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,henko_riyu,saishin_data_flg,zougen_hokoku_flg,shinki_flg,kaiyaku_flg,zenkai_hanbaiten_id,zenkai_dokusya_busu,zenkai_yubin_no,zenkai_todofuken_code,zenkai_shikuchoson,zenkai_chome_banchi,zenkai_tatemono_mei,denshi_shonin_status,hanbaiten_tekiyo_date,created_at,created_by) VALUES ('397', '172', '1', '108', '166', '166', '', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '3', '1000000', '01', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ thứ 2', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '24', '164', '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '', 'false', 'true', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-30 01:33:21.721161+09', '29');
INSERT INTO t_dokusya_rireki (dokusya_rireki_id,dokusya_id,rireki_no,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,henko_riyu,saishin_data_flg,zougen_hokoku_flg,shinki_flg,kaiyaku_flg,zenkai_hanbaiten_id,zenkai_dokusya_busu,zenkai_yubin_no,zenkai_todofuken_code,zenkai_shikuchoson,zenkai_chome_banchi,zenkai_tatemono_mei,denshi_shonin_status,hanbaiten_tekiyo_date,created_at,created_by) VALUES ('398', '173', '1', '108', '166', '166', 'TC-0000002', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '5', '1000001', '02', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '25', '164', '0', '3', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '', 'true', 'true', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-30 01:35:41.014243+09', '29');
INSERT INTO t_dokusya_rireki (dokusya_rireki_id,dokusya_id,rireki_no,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,henko_riyu,saishin_data_flg,zougen_hokoku_flg,shinki_flg,kaiyaku_flg,zenkai_hanbaiten_id,zenkai_dokusya_busu,zenkai_yubin_no,zenkai_todofuken_code,zenkai_shikuchoson,zenkai_chome_banchi,zenkai_tatemono_mei,denshi_shonin_status,hanbaiten_tekiyo_date,created_at,created_by) VALUES ('399', '174', '1', '108', '166', '166', 'TC-0000003', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '2', '1000003', '01', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '24', '167', '0', '5', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '', '', '', 'true', 'true', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-30 01:45:14.520668+09', '29');
INSERT INTO t_dokusya_rireki (dokusya_rireki_id,dokusya_id,rireki_no,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,henko_riyu,saishin_data_flg,zougen_hokoku_flg,shinki_flg,kaiyaku_flg,zenkai_hanbaiten_id,zenkai_dokusya_busu,zenkai_yubin_no,zenkai_todofuken_code,zenkai_shikuchoson,zenkai_chome_banchi,zenkai_tatemono_mei,denshi_shonin_status,hanbaiten_tekiyo_date,created_at,created_by) VALUES ('400', '175', '1', '108', '166', '166', 'TC-0000004', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '1', '1000004', '02', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '24', '167', '0', '5', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '', 'true', 'true', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-30 01:48:04.762104+09', '29');
INSERT INTO t_dokusya_rireki (dokusya_rireki_id,dokusya_id,rireki_no,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,henko_riyu,saishin_data_flg,zougen_hokoku_flg,shinki_flg,kaiyaku_flg,zenkai_hanbaiten_id,zenkai_dokusya_busu,zenkai_yubin_no,zenkai_todofuken_code,zenkai_shikuchoson,zenkai_chome_banchi,zenkai_tatemono_mei,denshi_shonin_status,hanbaiten_tekiyo_date,created_at,created_by) VALUES ('401', '176', '1', '108', '167', '167', 'TC-0000005', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '6', '1000006', '04', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'false', '1133333', '03', 'Phường Từ Liêm', 'Địa chỉ haitatsu thứ 1', '', 'LH haitatsu 1', '', '今日', '今日', 'べとなむ', 'べとなむ', '24', '166', '0', '5', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '', 'false', 'true', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-30 02:07:01.731606+09', '29');
INSERT INTO t_dokusya_rireki (dokusya_rireki_id,dokusya_id,rireki_no,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,henko_riyu,saishin_data_flg,zougen_hokoku_flg,shinki_flg,kaiyaku_flg,zenkai_hanbaiten_id,zenkai_dokusya_busu,zenkai_yubin_no,zenkai_todofuken_code,zenkai_shikuchoson,zenkai_chome_banchi,zenkai_tatemono_mei,denshi_shonin_status,hanbaiten_tekiyo_date,created_at,created_by) VALUES ('402', '172', '2', '108', '166', '166', '', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '3', '1000000', '02', 'Phường Hà Đông', 'Địa chỉ thứ 2', '', 'DC-LH-002', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'true', '', '', '', '', '', '', '', '', '', '', '', '24', '164', '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '', 'true', 'true', 'false', 'false', NULL, NULL, '1000000', '01', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', NULL, NULL, '2026-06-30 02:26:55.481488+09', '29');
INSERT INTO t_dokusya_rireki (dokusya_rireki_id,dokusya_id,rireki_no,ja_id,kanri_shiten_id,shiten_id,kumiaiin_code,dokusya_shubetsu,tetsuzuki_shurui,denshi_dokusya_shubetsu,shimei_sei,shimei_mei,shimei_kana_sei,shimei_kana_mei,dokusya_busu,yubin_no,todofuken_code,shikuchoson,chome_banchi,tatemono_mei,renrakusaki_1,renrakusaki_2,email,mail_magazine_flg,birth_year,gender,haitatsu_same_flg,haitatsu_yubin_no,haitatsu_todofuken_code,haitatsu_shikuchoson,haitatsu_chome_banchi,haitatsu_tatemono_mei,haitatsu_renrakusaki_1,haitatsu_renrakusaki_2,haitatsu_shimei_sei,haitatsu_shimei_mei,haitatsu_shimei_kana_sei,haitatsu_shimei_kana_mei,hanbaiten_id,tanka_id,yubin_kubun,shiharai_hoho,dokusyaryo_shiharai_cycle,bank_branch_code,bank_branch_name,hikiotoshi_yokin_shubetsu,hikiotoshi_koza_no,hikiotoshi_koza_meigi,dokusyaso_bunrui,nogyosya_bunrui,shoki_dokusya_kaishi_date,dokusya_kaishi_date,dokusya_chushi_date,joho_henko_tekiyo_date,seikyu_kaishi_month,biko,henko_riyu,saishin_data_flg,zougen_hokoku_flg,shinki_flg,kaiyaku_flg,zenkai_hanbaiten_id,zenkai_dokusya_busu,zenkai_yubin_no,zenkai_todofuken_code,zenkai_shikuchoson,zenkai_chome_banchi,zenkai_tatemono_mei,denshi_shonin_status,hanbaiten_tekiyo_date,created_at,created_by) VALUES ('403', '176', '2', '108', '167', '167', 'TC-0000005', '1', '1', NULL, '今日', '今日', 'べとなむ', 'べとなむ', '6', '1000006', '04', 'Phường Từ Liêm', 'Địa chỉ đầu tiên', '', 'Liên hệ đây', '', 'vuanhquang0401@gmail.com', '0', NULL, NULL, 'false', '1133333', '05', 'Phường Đông Anh', 'Địa chỉ haitatsu thứ 2', '', 'LH haitatsu 2', '', '今日', '今日', 'べとなむ', 'べとなむ', '24', '166', '0', '5', NULL, '', '', NULL, '', '', '', '', '2026-06-30', '2026-06-30', NULL, '2026-06-30', '', '', '', 'true', 'true', 'false', 'false', NULL, NULL, '1133333', '03', 'Phường Từ Liêm', 'Địa chỉ haitatsu thứ 1', '', NULL, NULL, '2026-06-30 02:49:48.856253+09', '29');


-- ── 3) Fix sequence (setval = MAX hiện có) ──────────────────────────────────
SELECT setval('public.m_ja_ja_id_seq',                       (SELECT GREATEST(COALESCE(MAX(ja_id),1),1)               FROM m_ja),               true);
SELECT setval('public.m_tanka_tanka_id_seq',                 (SELECT GREATEST(COALESCE(MAX(tanka_id),1),1)            FROM m_tanka),            true);
SELECT setval('public.m_kanri_shiten_kanri_shiten_id_seq',   (SELECT GREATEST(COALESCE(MAX(kanri_shiten_id),1),1)     FROM m_kanri_shiten),     true);
SELECT setval('public.m_shiten_shiten_id_seq',                 (SELECT GREATEST(COALESCE(MAX(shiten_id),1),1)           FROM m_shiten),           true);
SELECT setval('public.m_hanbaiten_hanbaiten_id_seq',         (SELECT GREATEST(COALESCE(MAX(hanbaiten_id),1),1)        FROM m_hanbaiten),        true);
SELECT setval('public.m_account_account_id_seq',             (SELECT GREATEST(COALESCE(MAX(account_id),1),1)          FROM m_account),          true);
SELECT setval('public.t_dokusya_dokusya_id_seq',             (SELECT GREATEST(COALESCE(MAX(dokusya_id),1),1)          FROM t_dokusya),          true);
SELECT setval('public.t_dokusya_rireki_dokusya_rireki_id_seq',(SELECT GREATEST(COALESCE(MAX(dokusya_rireki_id),1),1)  FROM t_dokusya_rireki),   true);

-- ── 4) Sanity check ─────────────────────────────────────────────────────────
DO $$
DECLARE v_ja BIGINT; v_d INT; v_r INT; v_h INT; v_t INT;
BEGIN
  SELECT ja_id INTO v_ja FROM m_ja WHERE ja_code='JAZG9001';
  SELECT count(*) INTO v_d FROM t_dokusya        WHERE ja_id=v_ja;
  SELECT count(*) INTO v_r FROM t_dokusya_rireki WHERE ja_id=v_ja;
  SELECT count(*) INTO v_h FROM m_hanbaiten      WHERE ja_id=v_ja;
  SELECT count(*) INTO v_t FROM m_tanka          WHERE ja_id=v_ja;
  RAISE NOTICE '[seed-chuokai-zg] ja_id=% / dokusya=% / rireki=% / hanbaiten=% / tanka=%', v_ja, v_d, v_r, v_h, v_t;
END $$;

COMMIT;
