-- ============================================================================
-- seed-chuokai-zg-freshid.sql  (AUTO-GENERATED từ seed-chuokai-zg-current.sql)
--   Nạp graph JAZG9001 (account chuokai_zg2/kanri_zgA/kanri_zgB) bằng ID MỚI
--   do sequence cấp; FK giải theo khóa nghiệp vụ. Dùng cho DB đã có ID trùng.
--   IDEMPOTENT: xóa graph theo ja_code + login_id rồi chèn lại.
-- ============================================================================

BEGIN;

-- ── 1) CLEANUP ──
DELETE FROM t_dokusya_rireki WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM t_dokusya        WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM t_mfa_otp   WHERE account_id IN (SELECT account_id FROM m_account WHERE login_id IN ('chuokai_zg','chuokai_zg2','kanri_zgA','kanri_zgB'));
DELETE FROM t_login_log WHERE account_id IN (SELECT account_id FROM m_account WHERE login_id IN ('chuokai_zg','chuokai_zg2','kanri_zgA','kanri_zgB'));
DELETE FROM t_log       WHERE account_id IN (SELECT account_id FROM m_account WHERE login_id IN ('chuokai_zg','chuokai_zg2','kanri_zgA','kanri_zgB')) OR ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM t_oshirase       WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM t_file_upload    WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM t_file_download  WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM m_account   WHERE login_id IN ('chuokai_zg','chuokai_zg2','kanri_zgA','kanri_zgB');
DELETE FROM m_hanbaiten WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM m_shiten    WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM m_tanka     WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM m_kanri_shiten WHERE ja_id IN (SELECT ja_id FROM m_ja WHERE ja_code IN ('JAZG9001'));
DELETE FROM m_ja        WHERE ja_code IN ('JAZG9001');

-- ── 2) INSERT (ID mới, FK theo natural key) ──

-- ---- m_ja ----
INSERT INTO public.m_ja (ja_code, ja_name, ja_name_kana, todofuken_code, yubin_no, address, tel, fax, email, tanto_busho, tanto_name, jastem_itakusha_code, jastem_itakusha_name, jastem_ja_code, jastem_ja_name, chuokai_flg, zei_kubun, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES ('JAZG9001', '増減検証JA', 'ｿﾞｳｹﾞﾝｹﾝｼｮｳｼﾞｪｲｴｰ', '13', '1000001', '東京都千代田区1-1-1', '030001300000000', '0300000002', '', '', '', 'JAJT0001', 'JA-JASTEM-ZG-0001', '0101', 'JA-JASTEM-ZG-00', 'f', '1', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-07-02 01:43:47.17925+09', '29');
SELECT ja_id AS jaid FROM m_ja WHERE ja_code = 'JAZG9001' \gset

-- ---- m_tanka ----
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T001', '1', '新聞購読料 月額', '3500', '3182', '10.00', '2026-01-10', NULL, '', 't', 'f', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T002', '2', '配達手数料 月額', '350', '318', '10.00', '2026-01-10', NULL, '', 't', 'f', NULL, '2026-06-26 03:32:15.684711+09', 'PATCH_2021', '2026-06-26 03:32:15.684711+09', 'PATCH_2021');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T003', '1', '新聞購読料 月額(セット)', '4200', '3819', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T004', '1', '新聞購読料 月額(統合版)', '3000', '2728', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T005', '1', '新聞購読料 月額(日曜版)', '1200', '1091', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T006', '1', '新聞購読料 月額(夕刊)', '1800', '1637', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T007', '1', '新聞購読料 月額(電子+紙)', '4800', '4365', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T008', '2', '配達手数料 月額(市内)', '400', '364', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T009', '2', '配達手数料 月額(郊外)', '600', '546', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T010', '2', '配達手数料 月額(山間部)', '1000', '909', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T011', '2', '配達手数料 月額(離島)', '1500', '1364', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_tanka (ja_id, tanka_code, tanka_type, tanka_name, kingaku_zeikomi, kingaku_zeinuki, tax_rate, tekiyo_start_date, tekiyo_end_date, biko, active_flg, campaign_flg, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'T012', '2', '配達手数料 月額(早朝便)', '700', '637', '10.00', '2025-04-01', NULL, '', 't', 'f', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
SELECT tanka_id AS tanka_1 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T001' \gset
SELECT tanka_id AS tanka_2 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T002' \gset
SELECT tanka_id AS tanka_3 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T003' \gset
SELECT tanka_id AS tanka_4 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T004' \gset
SELECT tanka_id AS tanka_5 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T005' \gset
SELECT tanka_id AS tanka_6 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T006' \gset
SELECT tanka_id AS tanka_7 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T007' \gset
SELECT tanka_id AS tanka_8 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T008' \gset
SELECT tanka_id AS tanka_9 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T009' \gset
SELECT tanka_id AS tanka_10 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T010' \gset
SELECT tanka_id AS tanka_11 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T011' \gset
SELECT tanka_id AS tanka_12 FROM m_tanka WHERE ja_id = :jaid AND tanka_code = 'T012' \gset

-- ---- m_kanri_shiten ----
INSERT INTO public.m_kanri_shiten (ja_id, kanri_shiten_code, kanri_shiten_name, kanri_shiten_name_kana, yubin_no, todofuken_code, address, tel, fax, paper_flg, denshi_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, '113-9001-001', '増減検証管理支店A', 'ｿﾞｳｹﾞﾝｹﾝｼｮｳｶﾝﾘｼﾃﾝｴｰ', '1000001', '13', '東京都千代田区A', '03-0000-1001', '03-0000-1002', 'f', 'f', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO public.m_kanri_shiten (ja_id, kanri_shiten_code, kanri_shiten_name, kanri_shiten_name_kana, yubin_no, todofuken_code, address, tel, fax, paper_flg, denshi_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, '113-9001-002', '増減検証管理支店B', 'ｿﾞｳｹﾞﾝｹﾝｼｮｳｶﾝﾘｼﾃﾝﾋﾞｰ', '1000001', '13', '東京都千代田区B', '03-0000-2001', '03-0000-2002', 'f', 'f', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
SELECT kanri_shiten_id AS ks_1 FROM m_kanri_shiten WHERE ja_id = :jaid AND kanri_shiten_code = '113-9001-001' \gset
SELECT kanri_shiten_id AS ks_2 FROM m_kanri_shiten WHERE ja_id = :jaid AND kanri_shiten_code = '113-9001-002' \gset

-- ---- m_shiten ----
INSERT INTO public.m_shiten (ja_id, shiten_code, shiten_name, shiten_name_kana, kinyu_shiten_flg, jastem_toriatsukai_tenpo_code, jastem_tenpo_name, jastem_tyokin_shubetsu, jastem_koza_no, kanri_shiten_id, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'ST9001', '増減検証支店A', 'ｿﾞｳｹﾞﾝｼﾃﾝｴｰ', 'f', '', '', '', '', :ks_1, '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO public.m_shiten (ja_id, shiten_code, shiten_name, shiten_name_kana, kinyu_shiten_flg, jastem_toriatsukai_tenpo_code, jastem_tenpo_name, jastem_tyokin_shubetsu, jastem_koza_no, kanri_shiten_id, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'ST9002', '増減検証支店B', 'ｿﾞｳｹﾞﾝｼﾃﾝﾋﾞｰ', 'f', '', '', '', '', :ks_2, '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO public.m_shiten (ja_id, shiten_code, shiten_name, shiten_name_kana, kinyu_shiten_flg, jastem_toriatsukai_tenpo_code, jastem_tenpo_name, jastem_tyokin_shubetsu, jastem_koza_no, kanri_shiten_id, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, '010', 'STBank', '', 't', '010', 'ABCE', '1', '1234456', :ks_1, '', NULL, '2026-06-26 02:44:08.834529+09', '29', '2026-06-26 02:44:08.834529+09', '29');
SELECT shiten_id AS sh_1 FROM m_shiten WHERE ja_id = :jaid AND shiten_code = 'ST9001' \gset
SELECT shiten_id AS sh_2 FROM m_shiten WHERE ja_id = :jaid AND shiten_code = 'ST9002' \gset
SELECT shiten_id AS sh_3 FROM m_shiten WHERE ja_id = :jaid AND shiten_code = '010' \gset

-- ---- m_hanbaiten ----
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB001', '増減販売店1', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ1', '', '13', '', '', '', '', '', '2', :tanka_2, '1', NULL, NULL, '0001', 'みずほ銀行', '001', '本店', '1', '9001', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ1', 'f', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB002', '増減販売店2', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ2', 'T1234567890123', '13', '', '', '', '', '', '1', :tanka_2, '3', NULL, NULL, '0001', 'みずほ銀行', '002', '丸の内', '1', '9002', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ2', 'f', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB003', '増減販売店3(廃店)', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ3', '', '13', '', '', '', '', '', '2', :tanka_2, '6', NULL, NULL, '0001', 'みずほ銀行', '003', '廃店', '1', '9003', 'ｿﾞｳｹﾞﾝﾊﾝﾊﾞｲﾃﾝ3', 't', '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-06-21 19:48:37.608732+09', 'SEED_ZG');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB004', '追加販売店4', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ4', 'T4000000000004', '13', '', '', '', '', '', '1', :tanka_8, NULL, NULL, NULL, '0001', 'みずほ銀行', '011', '秋葉原', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB005', '追加販売店5', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ5', 'T4000000000005', '13', '', '', '', '', '', '1', :tanka_8, NULL, NULL, NULL, '0005', '三菱UFJ銀行', '012', '上野', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB006', '追加販売店6', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ6', 'T4000000000006', '13', '', '', '', '', '', '1', :tanka_8, NULL, NULL, NULL, '0009', '三井住友銀行', '013', '浅草', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB007', '追加販売店7', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ7', 'T4000000000007', '13', '', '', '', '', '', '1', :tanka_8, NULL, NULL, NULL, '0001', 'みずほ銀行', '014', '錦糸町', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB008', '追加販売店8', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ8', 'T4000000000008', '13', '', '', '', '', '', '2', :tanka_8, NULL, NULL, NULL, '0005', '三菱UFJ銀行', '015', '新宿', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB009', '追加販売店9', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ9', 'T4000000000009', '13', '', '', '', '', '', '2', :tanka_8, NULL, NULL, NULL, '0009', '三井住友銀行', '016', '渋谷', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB010', '追加販売店10', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ10', 'T4000000000010', '13', '', '', '', '', '', '1', :tanka_8, NULL, NULL, NULL, '0001', 'みずほ銀行', '017', '池袋', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB011', '追加販売店11', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ11', 'T4000000000011', '13', '', '', '', '', '', '1', :tanka_8, NULL, NULL, NULL, '0005', '三菱UFJ銀行', '018', '品川', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB012', '追加販売店12', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ12', 'T4000000000012', '13', '', '', '', '', '', '2', :tanka_8, NULL, NULL, NULL, '0009', '三井住友銀行', '019', '目黒', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
INSERT INTO public.m_hanbaiten (ja_id, hanbaiten_code, hanbaiten_name, hanbaiten_name_kana, torihikisaki_no, todofuken_code, yubin_no, address, tel, fax, shocho_name, itaku_kubun, haitatsuryo_tanka_id, haitatsuryo_shiharai_cycle, furikomi_tesuryo_futan_kubun, furikomi_tesuryo, bank_code, bank_name, bank_branch_code, bank_branch_name, yokin_shubetsu, koza_no, koza_meigi, haiten_flg, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES (:jaid, 'HB013', '追加販売店13', 'ﾂｲｶﾊﾝﾊﾞｲﾃﾝ13', 'T4000000000013', '13', '', '', '', '', '', '1', :tanka_8, NULL, NULL, NULL, '0001', 'みずほ銀行', '020', '中野', NULL, '', '', 'f', '', NULL, '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10', '2026-06-30 01:12:13.069938+09', 'PATCH_ADD10');
SELECT hanbaiten_id AS hb_1 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB001' \gset
SELECT hanbaiten_id AS hb_2 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB002' \gset
SELECT hanbaiten_id AS hb_3 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB003' \gset
SELECT hanbaiten_id AS hb_4 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB004' \gset
SELECT hanbaiten_id AS hb_5 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB005' \gset
SELECT hanbaiten_id AS hb_6 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB006' \gset
SELECT hanbaiten_id AS hb_7 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB007' \gset
SELECT hanbaiten_id AS hb_8 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB008' \gset
SELECT hanbaiten_id AS hb_9 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB009' \gset
SELECT hanbaiten_id AS hb_10 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB010' \gset
SELECT hanbaiten_id AS hb_11 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB011' \gset
SELECT hanbaiten_id AS hb_12 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB012' \gset
SELECT hanbaiten_id AS hb_13 FROM m_hanbaiten WHERE ja_id = :jaid AND hanbaiten_code = 'HB013' \gset

-- ---- m_account ----
INSERT INTO public.m_account (login_id, password_hash, account_name, role_id, ja_id, kanri_shiten_id, todofuken_code, paper_flg, denshi_flg, email, sub_email_1, sub_email_2, sub_email_3, password_updated_at, last_login_at, login_failure_count, mfa_enable_flg, account_lock_flg, account_lock_at, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES ('chuokai_zg2', '$2b$10$n4LPqi8Ix8.LVTNqeIZJb.aKAdY8mGfrwbiCxdQ17E7bLPY/24qaG', '増減検証中央会アカウント', '3', :jaid, NULL, '13', 't', 't', 'chuokai_zg2@agrinews.jp', '', '', '', NULL, '2026-07-02 02:52:08.332+09', '0', 'f', 'f', NULL, '', NULL, '2026-06-21 19:48:37.608732+09', 'SEED_ZG', '2026-07-02 02:52:08.333511+09', 'SEED_ZG');
INSERT INTO public.m_account (login_id, password_hash, account_name, role_id, ja_id, kanri_shiten_id, todofuken_code, paper_flg, denshi_flg, email, sub_email_1, sub_email_2, sub_email_3, password_updated_at, last_login_at, login_failure_count, mfa_enable_flg, account_lock_flg, account_lock_at, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES ('kanri_zgA', '$2b$10$u9DubcTeb8.pUOemnjKHNuIBfUha3T0YqGU7r1YCcIZxch2oN/x5u', 'JA東京都A', '5', :jaid, :ks_1, '13', 't', 't', 'kanri_zgA@gmail.com', '', '', '', NULL, NULL, '0', 'f', 'f', NULL, '', NULL, '2026-07-02 02:49:13.86249+09', '2', '2026-07-02 02:49:13.86249+09', '2');
INSERT INTO public.m_account (login_id, password_hash, account_name, role_id, ja_id, kanri_shiten_id, todofuken_code, paper_flg, denshi_flg, email, sub_email_1, sub_email_2, sub_email_3, password_updated_at, last_login_at, login_failure_count, mfa_enable_flg, account_lock_flg, account_lock_at, biko, deleted_at, created_at, created_by, updated_at, updated_by) VALUES ('kanri_zgB', '$2b$10$xirxbV.6.tmDtylO4J5bjeT9OQpAooFHooRLXY2SJXF0pnjnm9sB6', 'JA東京都B', '5', :jaid, :ks_2, '13', 't', 't', 'kanri_zgB@gmail.com', '', '', '', NULL, NULL, '0', 'f', 'f', NULL, '', NULL, '2026-07-02 02:50:09.467269+09', '2', '2026-07-02 02:50:09.467269+09', '2');

-- ---- t_dokusya ----
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_1, :sh_1, 'DOKU01', '1', '1', NULL, '田中', '太郎', 'ﾀﾅｶ', 'ﾀﾛｳ', '2', '1000001', '13', '千代田区', '1-1-1', '', '090-1000-0001', '', '', '0', '1975', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_1, '0', '1', '1', '001', '本店', '1', '1234567', 'ﾀﾅｶ ﾀﾛｳ', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '1', NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10', '2026-07-03 00:00:00+09', 'SEED_DOKU10', NULL, NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_1, :sh_1, 'DOKU02', '1', '1', NULL, '佐藤', '花子', 'ｻﾄｳ', 'ﾊﾅｺ', '1', '1000001', '13', '千代田区', '1-1-2', '', '090-1000-0002', '', '', '0', '1982', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '1', NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10', '2026-07-03 00:00:00+09', 'SEED_DOKU10', NULL, NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_1, :sh_1, 'DOKU03', '2', '1', NULL, '鈴木', '一郎', 'ｽｽﾞｷ', 'ｲﾁﾛｳ', '1', '1000001', '13', '千代田区', '1-1-3', '', '090-1000-0003', '', 'doku03.suzuki@example.jp', '1', '1968', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_2, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-08', '202607', '', '2', NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10', '2026-07-02 03:29:05.778978+09', '29', '1', NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_1, :sh_1, 'DOKU04', '1', '1', NULL, '高橋', '恵子', 'ﾀｶﾊｼ', 'ｹｲｺ', '3', '1000001', '13', '千代田区', '1-1-4', '', '090-1000-0004', '', '', '0', '1990', '2', 'f', '1000002', '02', '千代田区2', '1-1-3', '', '', '', '高橋', '恵子', 'たかはし', 'たかはし', :hb_2, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-08', '202607', '', '2', NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10', '2026-07-02 03:31:42.422631+09', '29', NULL, NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_1, :sh_1, 'DOKU05', '1', '1', NULL, '渡辺', '健', 'ﾜﾀﾅﾍﾞ', 'ｹﾝ', '2', '1000004', '09', '千代田区1-3', '1-1-8', '', '090-1000-0004', '', '', '0', '1971', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-08', '202607', '', '2', NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10', '2026-07-02 03:32:14.771959+09', '29', NULL, NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_2, :sh_2, 'DOKU06', '1', '1', NULL, '伊藤', '幸子', 'ｲﾄｳ', 'ｻﾁｺ', '4', '1000001', '13', '千代田区', '1-1-6', '', '090-1000-0006', '', '', '0', '1985', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '1', '1', '010', 'ABCE', '1', '2345678', 'ｲﾄｳ ｻﾁｺ', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '2', NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10', '2026-07-02 03:26:54.817956+09', '29', NULL, NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_2, :sh_2, 'DOKU07', '1', '1', NULL, '山本', '実', 'ﾔﾏﾓﾄ', 'ﾐﾉﾙ', '1', '1000001', '13', '千代田区', '1-1-7', '', '090-1000-0007', '', '', '0', '1960', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '1', NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10', '2026-07-03 00:00:00+09', 'SEED_DOKU10', NULL, NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_2, :sh_2, 'DOKU08', '2', '1', NULL, '中村', '京子', 'ﾅｶﾑﾗ', 'ｷｮｳｺ', '1', '1000001', '13', '千代田区', '1-1-8', '', '090-1000-0008', '', 'doku08.nakamura@example.jp', '1', '1978', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_2, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-08', '2026-07-08', NULL, '2026-07-08', '202607', '', '1', NULL, '2026-07-08 00:00:00+09', 'SEED_DOKU10', '2026-07-08 00:00:00+09', 'SEED_DOKU10', '1', NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_2, :sh_2, 'DOKU09', '1', '1', NULL, '小林', '修', 'ｺﾊﾞﾔｼ', 'ｵｻﾑ', '4', '1000001', '13', '千代田区', '1-1-9', '', '090-1000-0009', '', '', '0', '1995', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-08', '2026-07-08', NULL, '2026-07-08', '202607', '', '3', NULL, '2026-07-08 00:00:00+09', 'SEED_DOKU10', '2026-07-02 03:41:44.172261+09', '29', NULL, NULL);
INSERT INTO public.t_dokusya (ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, rireki_no, deleted_at, created_at, created_by, updated_at, updated_by, denshi_shonin_status, denshi_kaiin_id) VALUES (:jaid, :ks_2, :sh_2, 'DOKU10', '1', '1', NULL, '加藤', '真理', 'ｶﾄｳ', 'ﾏﾘ', '2', '1000001', '13', '千代田区', '1-1-10', '', '090-1000-0010', '', '', '0', '1988', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '1', '1', '010', 'ABCE', '1', '3456789', 'ｶﾄｳ ﾏﾘ', '', '', '2026-07-08', '2026-07-08', NULL, '2026-07-02', '202607', '', '2', NULL, '2026-07-08 00:00:00+09', 'SEED_DOKU10', '2026-07-02 03:26:25.925645+09', '29', NULL, NULL);
SELECT dokusya_id AS dok_1 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU01' \gset
SELECT dokusya_id AS dok_2 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU02' \gset
SELECT dokusya_id AS dok_3 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU03' \gset
SELECT dokusya_id AS dok_4 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU04' \gset
SELECT dokusya_id AS dok_5 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU05' \gset
SELECT dokusya_id AS dok_6 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU06' \gset
SELECT dokusya_id AS dok_7 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU07' \gset
SELECT dokusya_id AS dok_8 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU08' \gset
SELECT dokusya_id AS dok_9 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU09' \gset
SELECT dokusya_id AS dok_10 FROM t_dokusya WHERE ja_id = :jaid AND kumiaiin_code = 'DOKU10' \gset

-- ---- t_dokusya_rireki ----
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_1, '1', :jaid, :ks_1, :sh_1, 'DOKU01', '1', '1', NULL, '田中', '太郎', 'ﾀﾅｶ', 'ﾀﾛｳ', '2', '1000001', '13', '千代田区', '1-1-1', '', '090-1000-0001', '', '', '0', '1975', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_1, '0', '1', '1', '001', '本店', '1', '1234567', 'ﾀﾅｶ ﾀﾛｳ', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 't', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_2, '1', :jaid, :ks_1, :sh_1, 'DOKU02', '1', '1', NULL, '佐藤', '花子', 'ｻﾄｳ', 'ﾊﾅｺ', '1', '1000001', '13', '千代田区', '1-1-2', '', '090-1000-0002', '', '', '0', '1982', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 't', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_3, '1', :jaid, :ks_1, :sh_1, 'DOKU03', '2', '1', NULL, '鈴木', '一郎', 'ｽｽﾞｷ', 'ｲﾁﾛｳ', '1', '1000001', '13', '千代田区', '1-1-3', '', '090-1000-0003', '', 'doku03.suzuki@example.jp', '1', '1968', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_2, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 'f', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_4, '1', :jaid, :ks_1, :sh_1, 'DOKU04', '1', '1', NULL, '高橋', '恵子', 'ﾀｶﾊｼ', 'ｹｲｺ', '3', '1000001', '13', '千代田区', '1-1-4', '', '090-1000-0004', '', '', '0', '1990', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 'f', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_5, '1', :jaid, :ks_1, :sh_1, 'DOKU05', '1', '1', NULL, '渡辺', '健', 'ﾜﾀﾅﾍﾞ', 'ｹﾝ', '2', '1000001', '13', '千代田区', '1-1-5', '', '090-1000-0005', '', '', '0', '1971', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 'f', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_6, '1', :jaid, :ks_2, :sh_2, 'DOKU06', '1', '1', NULL, '伊藤', '幸子', 'ｲﾄｳ', 'ｻﾁｺ', '4', '1000001', '13', '千代田区', '1-1-6', '', '090-1000-0006', '', '', '0', '1985', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '1', '1', '001', '本店', '1', '2345678', 'ｲﾄｳ ｻﾁｺ', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 'f', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_7, '1', :jaid, :ks_2, :sh_2, 'DOKU07', '1', '1', NULL, '山本', '実', 'ﾔﾏﾓﾄ', 'ﾐﾉﾙ', '1', '1000001', '13', '千代田区', '1-1-7', '', '090-1000-0007', '', '', '0', '1960', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 't', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-03 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_8, '1', :jaid, :ks_2, :sh_2, 'DOKU08', '2', '1', NULL, '中村', '京子', 'ﾅｶﾑﾗ', 'ｷｮｳｺ', '1', '1000001', '13', '千代田区', '1-1-8', '', '090-1000-0008', '', 'doku08.nakamura@example.jp', '1', '1978', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_2, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-08', '2026-07-08', NULL, '2026-07-08', '202607', '', '', 't', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, '2026-07-08 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_9, '1', :jaid, :ks_2, :sh_2, 'DOKU09', '1', '1', NULL, '小林', '修', 'ｺﾊﾞﾔｼ', 'ｵｻﾑ', '3', '1000001', '13', '千代田区', '1-1-9', '', '090-1000-0009', '', '', '0', '1995', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 'f', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-08 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_10, '1', :jaid, :ks_2, :sh_2, 'DOKU10', '1', '1', NULL, '加藤', '真理', 'ｶﾄｳ', 'ﾏﾘ', '2', '1000001', '13', '千代田区', '1-1-10', '', '090-1000-0010', '', '', '0', '1988', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '1', '1', '001', '本店', '1', '3456789', 'ｶﾄｳ ﾏﾘ', '', '', '2026-07-08', '2026-07-08', NULL, '2026-07-08', '202607', '', '', 'f', 't', 't', 'f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-07-08 00:00:00+09', 'SEED_DOKU10');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_10, '2', :jaid, :ks_2, :sh_2, 'DOKU10', '1', '1', NULL, '加藤', '真理', 'ｶﾄｳ', 'ﾏﾘ', '2', '1000001', '13', '千代田区', '1-1-10', '', '090-1000-0010', '', '', '0', '1988', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '1', '1', '010', 'ABCE', '1', '3456789', 'ｶﾄｳ ﾏﾘ', '', '', '2026-07-08', '2026-07-08', NULL, '2026-07-02', '202607', '', '', 't', 'f', 'f', 'f', :hb_2, '2', '1000001', '13', '千代田区', '1-1-10', '', NULL, NULL, '2026-07-02 03:26:25.925645+09', '29');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_6, '2', :jaid, :ks_2, :sh_2, 'DOKU06', '1', '1', NULL, '伊藤', '幸子', 'ｲﾄｳ', 'ｻﾁｺ', '4', '1000001', '13', '千代田区', '1-1-6', '', '090-1000-0006', '', '', '0', '1985', '2', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '1', '1', '010', 'ABCE', '1', '2345678', 'ｲﾄｳ ｻﾁｺ', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-03', '202607', '', '', 't', 'f', 'f', 'f', :hb_2, '4', '1000001', '13', '千代田区', '1-1-6', '', NULL, NULL, '2026-07-02 03:26:54.817956+09', '29');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_9, '2', :jaid, :ks_2, :sh_2, 'DOKU09', '1', '1', NULL, '小林', '修', 'ｺﾊﾞﾔｼ', 'ｵｻﾑ', '3', '1000001', '13', '千代田区', '1-1-9', '', '090-1000-0009', '', '', '0', '1995', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-08', '202607', '', '', 'f', 't', 'f', 'f', :hb_1, '3', '1000001', '13', '千代田区', '1-1-9', '', NULL, '2026-07-08', '2026-07-02 03:28:36.112131+09', '29');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_3, '2', :jaid, :ks_1, :sh_1, 'DOKU03', '2', '1', NULL, '鈴木', '一郎', 'ｽｽﾞｷ', 'ｲﾁﾛｳ', '1', '1000001', '13', '千代田区', '1-1-3', '', '090-1000-0003', '', 'doku03.suzuki@example.jp', '1', '1968', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_2, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-08', '202607', '', '', 't', 't', 'f', 'f', :hb_1, '1', '1000001', '13', '千代田区', '1-1-3', '', '1', '2026-07-08', '2026-07-02 03:29:05.778978+09', '29');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_4, '2', :jaid, :ks_1, :sh_1, 'DOKU04', '1', '1', NULL, '高橋', '恵子', 'ﾀｶﾊｼ', 'ｹｲｺ', '3', '1000001', '13', '千代田区', '1-1-4', '', '090-1000-0004', '', '', '0', '1990', '2', 'f', '1000002', '02', '千代田区2', '1-1-3', '', '', '', '高橋', '恵子', 'たかはし', 'たかはし', :hb_2, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-08', '202607', '', '', 't', 't', 'f', 'f', :hb_2, '3', '1000001', '13', '千代田区', '1-1-4', '', NULL, NULL, '2026-07-02 03:31:42.422631+09', '29');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_5, '2', :jaid, :ks_1, :sh_1, 'DOKU05', '1', '1', NULL, '渡辺', '健', 'ﾜﾀﾅﾍﾞ', 'ｹﾝ', '2', '1000004', '09', '千代田区1-3', '1-1-8', '', '090-1000-0004', '', '', '0', '1971', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_1, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-08', '202607', '', '', 't', 't', 'f', 'f', :hb_1, '2', '1000001', '13', '千代田区', '1-1-5', '', NULL, NULL, '2026-07-02 03:32:14.771959+09', '29');
INSERT INTO public.t_dokusya_rireki (dokusya_id, rireki_no, ja_id, kanri_shiten_id, shiten_id, kumiaiin_code, dokusya_shubetsu, tetsuzuki_shurui, denshi_dokusya_shubetsu, shimei_sei, shimei_mei, shimei_kana_sei, shimei_kana_mei, dokusya_busu, yubin_no, todofuken_code, shikuchoson, chome_banchi, tatemono_mei, renrakusaki_1, renrakusaki_2, email, mail_magazine_flg, birth_year, gender, haitatsu_same_flg, haitatsu_yubin_no, haitatsu_todofuken_code, haitatsu_shikuchoson, haitatsu_chome_banchi, haitatsu_tatemono_mei, haitatsu_renrakusaki_1, haitatsu_renrakusaki_2, haitatsu_shimei_sei, haitatsu_shimei_mei, haitatsu_shimei_kana_sei, haitatsu_shimei_kana_mei, hanbaiten_id, tanka_id, yubin_kubun, shiharai_hoho, dokusyaryo_shiharai_cycle, bank_branch_code, bank_branch_name, hikiotoshi_yokin_shubetsu, hikiotoshi_koza_no, hikiotoshi_koza_meigi, dokusyaso_bunrui, nogyosya_bunrui, shoki_dokusya_kaishi_date, dokusya_kaishi_date, dokusya_chushi_date, joho_henko_tekiyo_date, seikyu_kaishi_month, biko, henko_riyu, saishin_data_flg, zougen_hokoku_flg, shinki_flg, kaiyaku_flg, zenkai_hanbaiten_id, zenkai_dokusya_busu, zenkai_yubin_no, zenkai_todofuken_code, zenkai_shikuchoson, zenkai_chome_banchi, zenkai_tatemono_mei, denshi_shonin_status, hanbaiten_tekiyo_date, created_at, created_by) VALUES (:dok_9, '3', :jaid, :ks_2, :sh_2, 'DOKU09', '1', '1', NULL, '小林', '修', 'ｺﾊﾞﾔｼ', 'ｵｻﾑ', '4', '1000001', '13', '千代田区', '1-1-9', '', '090-1000-0009', '', '', '0', '1995', '1', 't', '', '', '', '', '', '', '', '', '', '', '', :hb_2, :tanka_1, '0', '2', NULL, '', '', NULL, '', '', '', '', '2026-07-03', '2026-07-03', NULL, '2026-07-08', '202607', '', '', 't', 't', 'f', 'f', :hb_2, '3', '1000001', '13', '千代田区', '1-1-9', '', NULL, NULL, '2026-07-02 03:41:44.172261+09', '29');

-- ── 3) Sanity check ──
DO $$
DECLARE v_ja BIGINT; v_d INT; v_r INT; v_h INT; v_t INT; v_a INT;
BEGIN
  SELECT ja_id INTO v_ja FROM m_ja WHERE ja_code='JAZG9001';
  SELECT count(*) INTO v_d FROM t_dokusya        WHERE ja_id=v_ja;
  SELECT count(*) INTO v_r FROM t_dokusya_rireki WHERE ja_id=v_ja;
  SELECT count(*) INTO v_h FROM m_hanbaiten      WHERE ja_id=v_ja;
  SELECT count(*) INTO v_t FROM m_tanka          WHERE ja_id=v_ja;
  SELECT count(*) INTO v_a FROM m_account        WHERE login_id IN ('chuokai_zg2','kanri_zgA','kanri_zgB');
  RAISE NOTICE '[freshid] ja_id=% / dokusya=% / rireki=% / hanbaiten=% / tanka=% / account=%',
    v_ja, v_d, v_r, v_h, v_t, v_a;
END $$;

COMMIT;
